apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mynginx-label
  name: mynginx
spec:
  containers:
  - name: mynginx
    image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: mynginx-svc
spec:
  type: ClusterIP
  selector:
    app: mynginx-label
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP

